services:
  mswtest:
    image: ${PROJECT_NAME}:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      PROJECT_NAME: ${PROJECT_NAME}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "server.js"]
