services:
  mswtest:
    image: mswtest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 9090:9090
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
