services:
  mswtest:
    image: mswtest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      HUSKY: 0
      SERVER_PORT: 8000
    ports:
      - 8000:8000
